### ISSUE TITLE
Battlenet Account Not Working (Possibly due to unsupported characters)

### ISSUE THREAD

**Issue by cburj** [BinarMorker/TimeWastedOnDestiny#53] opened 2017-10-28 13:28 UTC
Battle Tag is cbürg#2114

I'm assuming that the ü is causing the problem.

**Comment by BinarMorker** [comment] 2017-10-28 20:10
It seems that battle tags with unicode characters don't work with either my search function or Bungie's search function. It might be something on their end. I will check.

**Comment by BinarMorker** [comment] 2017-10-28 20:13
https://github.com/Bungie-net/api/issues/266

**Comment by BinarMorker** [comment] 2017-11-26 19:36
The problem is now fixed.

**Closed by BinarMorker** 2017-11-26 19:36 UTC
